[plugin]
id = "ai-wso2-integration-compiler-plugin"
class = "io.ballerinax.ai.wso2.integration.plugin.AiWso2IntegrationCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai.wso2.integration-compiler-plugin-@project.version@.jar"
