/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package io.ballerinax.ai.wso2.integration.plugin.endpointyaml.generator;

import io.ballerina.projects.plugins.CompilerLifecycleEventContext;
import io.ballerina.projects.plugins.CompilerLifecycleTask;
import io.ballerina.projects.plugins.EndpointMetaInfo;
import io.ballerinax.ai.wso2.integration.plugin.PluginConstants;

import java.util.List;
import java.util.Map;

/**
 * Hands every {@link Endpoint} collected during code analysis to ballerina-lang as an {@link
 * EndpointMetaInfo}, once for the whole compilation after code generation completes; ballerina-lang
 * then writes them into the {@code endpoints.yaml} generated by {@code bal build --export-endpoints}.
 * Endpoints are only collected on distributions that provide this API (2201.13.6+), see {@code
 * VoiceServiceAnalysisTask}.
 */
public class EndpointMetadataTask implements CompilerLifecycleTask<CompilerLifecycleEventContext> {

    private final Map<String, Object> ctxData;

    public EndpointMetadataTask(Map<String, Object> ctxData) {
        this.ctxData = ctxData;
    }

    @Override
    @SuppressWarnings("unchecked")
    public void perform(CompilerLifecycleEventContext context) {
        List<Endpoint> endpoints = (List<Endpoint>) ctxData.get(PluginConstants.CTX_DATA_ENDPOINTS);
        if (endpoints == null) {
            return;
        }
        for (Endpoint endpoint : endpoints) {
            context.addEndpointMetadata(new EndpointMetaInfo(endpoint.getName(), endpoint.getPort(),
                    endpoint.getBasePath(), endpoint.getType(), endpoint.getSchemaPath()));
        }
    }
}
